version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: raw data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales infomation
        columns:
          - name: date_date
            description: date
          - name: orders_id
            description: orders id
          - name: pdt_id AS product_id
            description: pdt id
          - name: revenue
            description: revenue
          - name: quantity
            description: quantity
      - name: product
        identifier: raw_product
        description: product information
        columns:
          - name: products_id
            description: product id
            tests:
              - unique
              - not_null
                
          - name: purchSE_PRICE AS purchase_price
            description: purchase price
      - name: ship
        identifier: raw_gz_ship
        description: ship information
        columns:
          - name: orders_id
            description: orders id
            tests:
              - unique
              - not_null
        
          - name: shipping_fee
            description: shipping fee
          - name: shipping_fee_1
            description: shipping fee 1
          - name: logCost
            description: log cost
          - name: ship_cost
            description: ship cost
models:
  - name: int_sales_margin
    description: this table includes margin calculation
    columns:
      - name: orders_id
        tests:
          - not_null
      - name: products_id
        # tests:
        # - not_null
      - name: margin
        description: revenue - purchase cost
        tests:
          - not_null
      - name: purchase_cost
        description: purchase price * quantity
        tests:
          - not_null
      - name: date_date
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null

models:
  - name: int_orders_margin
    description: margin calcultation per order 
    columns:
      - name: order_id
        description: primary key
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price 
      - name: date_date
        description: date of the order
      - name: revenue
        description: sum of revenue per order 
      - name: quantity
        description: sum of quantity per order